//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public Pets()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int PetID { get; set; }
        public int ClientID { get; set; }
        public string Name { get; set; }
        public string Species { get; set; }
        public string Breed { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
