//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitServices
    {
        public int VisitServiceID { get; set; }
        public int VisitID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Visits Visits { get; set; }
    }
}
