//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        public Visits()
        {
            this.VisitServices = new HashSet<VisitServices>();
        }
    
        public int VisitID { get; set; }
        public int PetID { get; set; }
        public int VeterinarianUserID { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Symptoms { get; set; }
        public string Diagnosis { get; set; }
        public string Prescription { get; set; }
    
        public virtual Pets Pets { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<VisitServices> VisitServices { get; set; }
    }
}
